apiVersion: ENC[AES256_GCM,data:9HE=,iv:+DZPZyRnT3jxuXm9KrPrH9KGDQ/IMYvaHEx/FOQyxls=,tag:h+uPFIsMY3nMkHRo3IzsMA==,type:str]
kind: ENC[AES256_GCM,data:6zkvzOnr,iv:4FHhUT6f4Nx9OH/VYp3gImEhsD2IbPDBxIqQlJBL0x0=,tag:dX4IU48gi/mOzgnveVM2pQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:aqJZYvtBd9qOMGR6XQ==,iv:35FlusJM/UHsGvvFaPli6ywwV1JQppwpq6P3512KYzU=,tag:O4MtwJXY4Di3lUXthCcs1w==,type:str]
    namespace: ENC[AES256_GCM,data:xG72S/+2Rq9uaQ==,iv:Z7ZHwkA1G6ChpZoVRxgrmIpmbWnjCmG+ZhPp71v/XU8=,tag:d9wxUUBVo4MZ4GxO21L58Q==,type:str]
type: ENC[AES256_GCM,data:jgLv6hQd,iv:M3x3X6Uqfn34En0gbdlDTFZjNzb+hOrPpG+MY/EEmDM=,tag:yLKcmX6hn9B7Z0wuMtGPLA==,type:str]
stringData:
    admin-user: ENC[AES256_GCM,data:Tl9hdWg=,iv:mmHlfebMcVneek5uFE31Esm1W/hLbwhlvYRpRKb+D7w=,tag:X3njwEiMzn0U8o19lxlm8Q==,type:str]
    admin-password: ENC[AES256_GCM,data:q+K959HVMcyvql99mgusvq2PxzatBuCB,iv:zt+ZNd+fDzrz9rSC4eok1cfBr2woOZ0NJmEtqwT2VoA=,tag:Uxm9YTn4Pl66Km0ICbtHSw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPOUhqN085S1dLbEIyU21w
            QktOMDhiRUt4Q2dzZ0NRNXdHOWd5amFYdmw4CitGS045OWNFaDFiTDRTdHVycXRy
            czhvZUUvWFBWSjJuWjBhQk9XOVpPZVkKLS0tIDY0dGlPMTBkbUlKRS8wRzVFcXBr
            YldHT05vdmFVU21ZN1QvbElzbFIvRzgK0ShE6S+6uGLQClBCDjFKsq0Us7LQlPrj
            i4w79TpqOuzlZ1gHwlyZnREl7dLpe24OsRrVKwYJ9O2ORxfWAkVBvA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nnmg6lemam8f87cfnhm3ffduptpjmjudq9cm064qtrkdl2jhq40qjpkaue
    lastmodified: "2026-06-16T16:24:58Z"
    mac: ENC[AES256_GCM,data:rY8rw3/qOGDeQTE++KP54cFXmJ8sWGfoinl5ZjhQmR4FvWTpJdVDbLT/14svU3TIvMWmqsmWXQo04XGzN1pcqjsk2KZtfzr/XiYSFjyqTdsjHJKRt4OVmX1JXLo4jvrDJBezKfCc4ejosmcrCeXWgJDQnnF/mMMHt2P3uz0+eVo=,iv:GrLk90vUd4wNOPB+MEIE3YZRwhBoV7rbHQkcmyWB4E8=,tag:K9k3gLxI4U0I6JxUKSxlTA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
