apiVersion: ENC[AES256_GCM,data:eLM=,iv:dVm6ocHGcJitG5Z1ijDU7nvGYkJUxQK3dN+K3OGyK/8=,tag:TXuW1iB7ORR83jJzx9UKrg==,type:str]
kind: ENC[AES256_GCM,data:bpgiQC6g,iv:li2H/NtQcYbmjj+L2caZhVLoaDfIdECf5hZCssHfQyw=,tag:rqX84jhmR8yObvWb1z49rA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:MBc9F1nstPFvr/a7NSY9QbiyW1MqtO0=,iv:YCm6n2Gekg5TpH4Fbf6pMJMiT6+E+ue22BGVJsCrrbg=,tag:64kqrVgX2I3BUbQWJa2eaA==,type:str]
    namespace: ENC[AES256_GCM,data:0cwN52hx+rPxUlg=,iv:hnEdENUqitsUpwxPem7hOt8NIo9SBczWxlFqID/6I4s=,tag:pzKPaH36mxnjCQ2P9LtZYQ==,type:str]
type: ENC[AES256_GCM,data:cXq+aXTd,iv:smJKZL7bmlv4XLro/38thCVKdAjy42x3Fyx9BDroovg=,tag:BFUCSC9fNs7Xj44zT6zUVg==,type:str]
stringData:
    api-key: ENC[AES256_GCM,data:xxYbiXFWoS+Il2OVKdcqGd0/xVURcF5qMrsazk21LzBudzFcpArlJ5tiyDH0N+qAk+9GGO9GrW1BxOwforsp3acT,iv:pDSf1XwxdWwp3mndot4DrfvCmk/MXDaxrpAJzhGwsDc=,tag:KgZRezA0BSbLRoc7Xdopkg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpSFdIMUVuQVoxa09qOXJr
            ckNWVmc1WDAvakJKaW9qOVZpVFVhUWJMbHhrCnJnWFdTR0hCZmZib0h4dW0zdSs0
            STB1dkJXVTZZaThVVldZNGYyeHlvckkKLS0tIGxWUHFXejByYUlhaVIySWZyUGJR
            MTV6RFV4SFlwbVRNOTZMZnNBYXRmb1kKFXpxjzzXpiR1VowSwdJROJC8AwmlfWxp
            qHbBv/ulH92HfJWdMLpUaktk2fTMYMpA17JZBPR8KuKHWQJvixS9cg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nnmg6lemam8f87cfnhm3ffduptpjmjudq9cm064qtrkdl2jhq40qjpkaue
    lastmodified: "2026-07-09T18:08:35Z"
    mac: ENC[AES256_GCM,data:bG/ldpq8r49vipqWEc+hGKocMWrLBaZ3O7pdnx/55YLk+CEgisqZDWn/tGs3UQgPVDkSGQzdWbg8N4d3QECUXvNhq9MzTIqSgUcALscJEbGU5EQ+Whae7PJJ2j+E9a0awBGmvCapCszfnqUqEy8BXdhM8+8St/r1iIizdZIl2JI=,iv:4yRRagabYoOPCMIperP2aTjFeS1Ej/MncHIG9jJjnwc=,tag:iu2CM9meYEn/Ne2+wM2mUA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
