# Tier 1 — top-level master. One Application per stack.
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/RootButcher/homelab-apps
    targetRevision: HEAD
    path: infra
    directory:
      recurse: false
      include: "app-of-apps.yaml"
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
# test stack — 
# Lives outside `infra` so it can be pruned/deleted 
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/RootButcher/homelab-apps
    targetRevision: HEAD
    path: test
    directory:
      recurse: false
      include: "app-of-apps.yaml"
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
# logging stack — observability apps Separated from `infra` because the
# observability layer depends on storage (rook-ceph / democratic-csi) provided
# by `infra` and benefits from its own lifecycle.
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: logging
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/RootButcher/homelab-apps
    targetRevision: HEAD
    path: logging
    directory:
      recurse: false
      include: "app-of-apps.yaml"
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true