apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: truenas-csi
resources:
  - truenas-csi-driver.yaml
  - config.yaml
  - storageclass.yaml
images:
  - name: ghcr.io/truenas/truenas-csi
    newTag: v1.1.1  # bump from latest TODO updater
