apiVersion: ENC[AES256_GCM,data:Jwg=,iv:+DxHTn5dR8eZY03skExxFxFBAzbWfRHLNL/5Zfr2iBE=,tag:lKE9vGrDkbmnjq9nhj/RJQ==,type:str]
kind: ENC[AES256_GCM,data:6sKHzNkW,iv:hglYjqEFRzJ+iyxWvo4RL2wM6p+1qSNjsNFV3py6sso=,tag:qbZh+tQOL0Z21OxeUSvMEg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:3crj71s=,iv:1RDgV2cwFRYMEwQSNzt+Rz3F79Iw4m3hq4CG2qcgtPc=,tag:uM5vYO4YNHhDk7BTaTqg7A==,type:str]
    namespace: ENC[AES256_GCM,data:meTZBGyzxCaR,iv:eobJ7OFOcLekkK4yizJ0RWmk/v6mBCNI9eXa+3uWNi0=,tag:Bjt3quUdUQpdQx3MuXY/3A==,type:str]
type: ENC[AES256_GCM,data:Xw7HhgHf,iv:avJuafEtUqIutBnQfYoWOv00Z0o8heib9Q2//p8tZIw=,tag:wLIIekSmFf0gSbWPeSHN7g==,type:str]
stringData:
    hello: ENC[AES256_GCM,data:mcAcud4v,iv:pvYuY8QSJbQhUb5VSiPAebT2XhsOJMo8OSMK/3n01/8=,tag:5DLq38O3DmH2cxx8rDk26A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvQ29kcFhFc1R0bUloOUNC
            cklGUHh1WVJPQ1c5RlNHOURENmFEcjBqZXpZCjFvdEN0Z016TEpWZ3dKemZwN3Zs
            MzJobWcxU2dxd0MyQVVLaHByc205ekUKLS0tIFNZTkxKK2VTeVZoOW1aSkl4d3J0
            T3d1N1VxOTByNFB4VkF4aHlKWTJ5OG8KSfe/ks0AFpvnG3wXd4D9c63HsU9xzdbm
            TB1fkNTtBAqcfkOFo8qDEbhiz/e6/RP+To9vqxCE/8HEyUTp7uJvWw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nnmg6lemam8f87cfnhm3ffduptpjmjudq9cm064qtrkdl2jhq40qjpkaue
    lastmodified: "2026-06-01T20:13:13Z"
    mac: ENC[AES256_GCM,data:6+Y6gkktuMASf5wTwJDZhISDBPrwb0Fus/JKUhhuMozFeee/rMdtuz1YM4d0VV3x75om4PyGHZ8yGVS6QA5xZPfGtO8Flhznrm6eIaODxlfVrvAxSD9GDjZ9yFDk0vRgfyp0xEVY2q8M0Dh+Q1IuXdm5pNUlGnpXOOJHtNE6kyM=,iv:4oPF/olwQ7z0yWV5wHzB4i8qn8bpXMlZrtROUlDwG48=,tag:A2tQoygjSORIzi/qNK9mWA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
