apiVersion: ENC[AES256_GCM,data:SI8=,iv:MDvDNkLku1VP5p2bX8aYR0g3prVYzAeNR+wQUAdN/4U=,tag:0TLM/gGQ1ZSZP93MMcMZmA==,type:str]
kind: ENC[AES256_GCM,data:x/i7oAPw,iv:JtmH4Y8CrCsn6ghHklezs2DTfPuxitZZ4q0xJrX4G/E=,tag:to3kupUq2VvTmQt07QmpCQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:FokzrriCz54SjEtpZA==,iv:5E/+owkIPAkq0gROKhInSBRSdz6j094zJf9KOkLe2ug=,tag:pLM/PAYPOZAaORFPJQ3cBQ==,type:str]
    namespace: ENC[AES256_GCM,data:9Yf4xxF0Ze4VYw==,iv:dsG6bQkCzjT3gBj2XgIiE+LlfQF1xKA7aVbjlx/+owc=,tag:eRxSFPgyhU2ZKbbohsrOww==,type:str]
type: ENC[AES256_GCM,data:XfBSXCSG,iv:IuQUC7/xC+PTz0+kN4BzK/ux0XeNVn8nfaQvT9rASo0=,tag:lY8pZemT3YZScm1aaI+ewA==,type:str]
stringData:
    admin-user: ENC[AES256_GCM,data:Czij/oA=,iv:VhJcFtd1jl+5c+/54FcaPCX3kzpyujGcROrvkQvmZ5Y=,tag:gTYlexfEH3DcvkhOiTWUPg==,type:str]
    admin-password: ENC[AES256_GCM,data:UyA5R68lrBf85Q==,iv:PZ6+nqsFzEVkwPcVvuJAejU/vnSQCmG0AS5j8ElRf3c=,tag:5Bv4GcBPfGaTZSgHuYnP6Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBua3lQZkNVUEtkVm9BRGRh
            Q1JEOTI3SlVUVmJIRFRmTU84Ykx6THdEajFvCmxWNnlVYlNLaXJJUS8wcFpTOTQ3
            N3F0VVlzMUZiY0YvNWxSK2JsL0dBZ3cKLS0tIHVleUxjQnVqNGxSRUNBemhzeU91
            SjAwNVVuSGtnTU8rWGlzeGRORk9QREEKiDtFefb97a31VWAyVdFf3sy2pGXPslNv
            Ai3h1wwjRLRdomSuGGJD9vL9Qu8MgcYbKMaq0/L0DzosXJ0NI3K3Xg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nnmg6lemam8f87cfnhm3ffduptpjmjudq9cm064qtrkdl2jhq40qjpkaue
    lastmodified: "2026-06-14T01:20:45Z"
    mac: ENC[AES256_GCM,data:TSldmUgb1z5Zq5KtidoFOMIr0GGFb7KADICKTdwH+9PwgBxwwGtq/SaizMNZkl799tCkRq8+6yaE5T0SR0zhNRytj2ccqbFG7tORM3arkCJFfjuOodB9/+tBGmWBi4Irfl08E6+OHa09/0UYztLDqhbRGWt8Sf34xDCyCZJQ5Jw=,iv:biNS5UTKobX7705bC1MlPLenja8a5aNgmNqv/OchGHg=,tag:pQzkJze4VMoK9/IaWrQ1EQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
