apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: graphite-exporter
  labels:
    app.kubernetes.io/name: graphite-exporter
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: graphite-exporter
  endpoints:
    - port: metrics
      interval: 15s
      path: /metrics
      honorLabels: true
  namespaceSelector:
    matchNames:
      - monitoring