apiVersion: ENC[AES256_GCM,data:k24=,iv:xv0Raw+1YagZa07jAZudET86klMTS96f89suSdBNitM=,tag:wj3key0WLz68sRsaSWkp4Q==,type:str]
kind: ENC[AES256_GCM,data:LH/OGNxN,iv:CdDaiyxyxM63lapIA06Q87dxUmjvJwXhlBnPjKbRrxA=,tag:Ynilw1bbbdiiFmnTS2FZJA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:MwZ3Tb7wrcf5NK/YKMnMG94=,iv:DDA77+/U6ZLiBf0GkBp0+3fwHWO1r8FbwXGs8cE7Mdg=,tag:xQP5vQUTlRgzGaE4uBDL0Q==,type:str]
    namespace: ENC[AES256_GCM,data:WeO3FXIi8FZf3fHxFXk=,iv:cNePOEmMCCIL4fa5UbY0nvnw/vlphTH6N1RXm5s8cM4=,tag:PZbeJrCGHa0yAg0REUDyBA==,type:str]
type: ENC[AES256_GCM,data:RGRHamkZ,iv:eufFCUIuiB6lV9f1s1rOtbuWD9b87OGO87APDvuznQ0=,tag:ihGUrapIeXE6fm5R3O0/6Q==,type:str]
stringData:
    api-token: ENC[AES256_GCM,data:g9YDBmLxMdkqSgBJcbQ52U6o5uyZpiM8vvOOwCov+DELQeS/IgejT0WLdT4UBFNFDUuV1mINxqdeEJpbJEpjeorC,iv:VvoOaQUYbDDhRZlPPaG8x61QLXRyjqd6qaVjAKWkbOE=,tag:G7jmlAkIf1olpq/zluasxQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkQ2E3RXJlMzlkc3ZtRDVM
            dnBTTWt3NHRUTXI1cVhNQTRPYVdKZUlTWWhvCko5L1BadkVZamI3TTZnZXU4c1FI
            eXRIbmRVd2VuWWF2UmlQSWdwSEE0NHMKLS0tIDBBUUZTYXE5UkpPNXlNSDZRZUhk
            aUlWM0JVb1ZYOWR3c2RoS2o1RmM4bE0KcJV1xPgvgYZOJZvP9fzuCTKnuZ4glQ1a
            HHgm1vsNYJDAb5Alzo0oGPYGwSigppHDMSS5+9hElIExF/RsuS82Pw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nnmg6lemam8f87cfnhm3ffduptpjmjudq9cm064qtrkdl2jhq40qjpkaue
    lastmodified: "2026-06-02T00:12:41Z"
    mac: ENC[AES256_GCM,data:dmVcFPObEXoF4GHxhG15m1aws5xYfqXUUBfyX56Wj5ygkXsaxLSNn4y5C3PTGjTUtBHyTCX96FJzQ0hs/XFpi9sLOqOIkM1WPykYIYB+io1IF24YVC8HmiqCabSULv7bDbAXtyFy7F35Ta/3pJ5Y8+Q7aCBTW0hVpFU2b8Vrvh4=,iv:9JcdgvmBzrdQk/Wrs4GTaxAxg5JKEkaM1Aal7W52V6Y=,tag:+eJIRNTNJbF8CY3ijzRwKw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
