# Shared SOPS-encrypted TrueNAS API token, consumed by the two democratic-csi releases.
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: democratic-csi
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  # No resources-finalizer
spec:
  project: infra
  destination:
    server: https://kubernetes.default.svc
    namespace: democratic-csi
  source:
    repoURL: https://github.com/RootButcher/homelab-apps
    targetRevision: HEAD
    path: infra/democratic-csi/secrets
    plugin:
      name: kustomize-sops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true