apiVersion: ENC[AES256_GCM,data:QDo=,iv:gXu+wypjmQYpU8W2KTFw810AntDjZiHrXTrmo/DmsUY=,tag:x+I5oUW0dsCLpYGhdz2a9A==,type:str]
kind: ENC[AES256_GCM,data:2/pQZtjc,iv:g0/bQt7gZqHmbNaHtxZ/8WGdYjiFeU9UsrVsFzubF8Q=,tag:rxuBeHim9AZEftLXaHpTmw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:fGGsn/EtCacIwZedkE2ZD1sKH9s=,iv:zGRsWIRRKjJBIMtlmVQOAP1LBcXOVGVMWYLE+jAa9ao=,tag:1P49pl9N3a4o0ZCQ3sp+rA==,type:str]
    namespace: ENC[AES256_GCM,data:XOEqI+ingaxLxpCI,iv:EkgDQWf7hvsyZReNmg7WWoIZM1xmQK9F1e/lrDOcXDw=,tag:Xrah8BQqaFvElNkTQeTjFg==,type:str]
type: ENC[AES256_GCM,data:guZsPLav,iv:q9M41ix0YwZctaBKH1admrUOS3A9Web7wyGlYs0mfZM=,tag:NtMrTqOxVdMmxsfp7VAA0g==,type:str]
stringData:
    api-token: ENC[AES256_GCM,data:/RJEdddTnm3sxn87zYylhsZF4KEO6efxuHtJKNS+4ODqPwF/L1I90p1WFRBEA8VP0meX8QQ=,iv:FbAsjdqHPzUcX4EGAIIQh73FAHL4UQkydEEs5rpjGEw=,tag:1E2EtD7tZyM7bx5GiYXM9w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHaEtvTTB2QmZCSlJEaWIw
            VVRyUEEvVlhxVGx1RUo0Y0ZrTG02WFBROEdzCmNDNHovdk5jMVVPMXpaWVNrWWNX
            TXdsbFZHcWt2NXJLYy91UDMyeW9NMXcKLS0tIHMrQm5jb2JCaDVYQitwdEV0OWdZ
            RndDTmpWNVBwbFQ5eWtZeU5OT2lIYkEKuMyHvCtR5gpcdq5l3xMKfRof+AaJmQGr
            tX1qf6Z0nxgjVdVQGkNQ4BOAt6FMn8QXwyryzmU4agvZsyYkfxYtcw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nnmg6lemam8f87cfnhm3ffduptpjmjudq9cm064qtrkdl2jhq40qjpkaue
    lastmodified: "2026-06-01T22:08:03Z"
    mac: ENC[AES256_GCM,data:a+30W0RwxGB7KEQ/Ffx27pG5U/hQskF8qYRp9llmlp8KOU7zj2m7L1YenTGcYyECmk3X2m65TMhleEAEFS2ct3FULW90uKhNhsblzI2S2iTtvYW9bLCREwKGQOOAdjCaMPztJ90wy1q3QcIKKccuyxrn2RmEFdZkzlXTh2XVrBA=,iv:k1YLGX+Eo5g26LvsFcpr5XlFVk28J0pWUMfi5nwLkeo=,tag:ik9l2SKgxZY8i3AqrJKSxg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
