csiDriver:
  name: org.democratic-csi.nfs

controller:
  driver:
    extraEnv:
      - name: TRUENAS_API_KEY
        valueFrom:
          secretKeyRef:
            name: truenas-api-token
            key: api-token
node:
  driver:
    extraEnv:
      - name: TRUENAS_API_KEY
        valueFrom:
          secretKeyRef:
            name: truenas-api-token
            key: api-token

storageClasses:
  - name: truenas-nfs
    defaultClass: false
    reclaimPolicy: Delete
    volumeBindingMode: Immediate
    allowVolumeExpansion: true
    mountOptions:
      - nfsvers=4.1
      - noatime

driver:
  config:
    driver: freenas-api-nfs
    instance_id:
    httpConnection:
      protocol: https
      host: 10.0.11.20
      port: 443
      apiKey: ${TRUENAS_API_KEY}
      allowInsecure: true
    sshConnection: {}
    zfs:
      datasetParentName: Vault/k8s/nfs
      detachedSnapshotsDatasetParentName: Vault/k8s/nfs-snaps
      datasetEnableQuotas: true
      datasetEnableReservation: false
      datasetPermissionsMode: "0777"
      datasetPermissionsUser: 0
      datasetPermissionsGroup: 0
    nfs:
      shareHost: 10.0.11.20
      shareAlldirs: false
      shareAllowedHosts: []
      shareAllowedNetworks:
        - 10.0.11.0/24
      shareMaprootUser: root
      shareMaprootGroup: wheel
      shareMapallUser: ""
      shareMapallGroup: ""
