csiDriver:
  name: org.democratic-csi.iscsi

# Source the TrueNAS API key from the shared sops-managed Secret.
controller:
  driver:
    extraEnv:
      - name: TRUENAS_API_KEY
        valueFrom:
          secretKeyRef:
            name: truenas-api-token
            key: api-token
node:
  driver:
    extraEnv:
      - name: TRUENAS_API_KEY
        valueFrom:
          secretKeyRef:
            name: truenas-api-token
            key: api-token

storageClasses:
  - name: truenas-iscsi
    defaultClass: false
    reclaimPolicy: Delete
    volumeBindingMode: Immediate
    allowVolumeExpansion: true
    parameters:
      fsType: ext4

# Connection + iSCSI config.
driver:
  config:
    driver: freenas-api-iscsi
    instance_id:
    httpConnection:
      protocol: https
      host: 10.0.11.20
      port: 443
      apiKey: ${TRUENAS_API_KEY}
      allowInsecure: true
    sshConnection: {}
    zfs:
      datasetParentName: Vault/k8s/iscsi
      detachedSnapshotsDatasetParentName: Vault/k8s/iscsi-snaps
      zvolEnableReservation: false
      zvolBlocksize: ""
    iscsi:
      targetPortal: "10.0.11.20:3260"
      targetPortals: []
      namePrefix: csi-
      nameSuffix: ""
      targetGroups:
        - targetGroupPortalGroup: 1
          targetGroupInitiatorGroup: 1
          targetGroupAuthType: None
      extentInsecureTpc: true
      extentXenCompat: false
      extentDisablePhysicalBlocksize: true
      extentBlocksize: 512
      extentRpm: "SSD"
      extentAvailThreshold: 0
