# Cloudflare API token (SOPS), consumed by the cert-manager ClusterIssuers.
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-secrets
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: infra
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  source:
    repoURL: https://github.com/RootButcher/homelab-apps
    targetRevision: HEAD
    path: infra/cert-manager/secrets
    plugin:
      name: kustomize-sops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true