apiVersion: ENC[AES256_GCM,data:QDo=,iv:gXu+wypjmQYpU8W2KTFw810AntDjZiHrXTrmo/DmsUY=,tag:x+I5oUW0dsCLpYGhdz2a9A==,type:str]
kind: ENC[AES256_GCM,data:2/pQZtjc,iv:g0/bQt7gZqHmbNaHtxZ/8WGdYjiFeU9UsrVsFzubF8Q=,tag:rxuBeHim9AZEftLXaHpTmw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:fGGsn/EtCacIwZedkE2ZD1sKH9s=,iv:zGRsWIRRKjJBIMtlmVQOAP1LBcXOVGVMWYLE+jAa9ao=,tag:1P49pl9N3a4o0ZCQ3sp+rA==,type:str]
    namespace: ENC[AES256_GCM,data:XOEqI+ingaxLxpCI,iv:EkgDQWf7hvsyZReNmg7WWoIZM1xmQK9F1e/lrDOcXDw=,tag:Xrah8BQqaFvElNkTQeTjFg==,type:str]
type: ENC[AES256_GCM,data:guZsPLav,iv:q9M41ix0YwZctaBKH1admrUOS3A9Web7wyGlYs0mfZM=,tag:NtMrTqOxVdMmxsfp7VAA0g==,type:str]
stringData:
    api-token: ENC[AES256_GCM,data:8AHQeTd82dT27okGKT+4pgwmk3XUHuWFxfbOS1mxvkf0WAv2VPUBtYghrQ4DGbUDjfE5LXc=,iv:IM+vor3gTF+lET3CVZam7HQjDxn7OPyfb40sKorrGxQ=,tag:IdXbEBhDsiap+LVil1UUMQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHaEtvTTB2QmZCSlJEaWIw
            VVRyUEEvVlhxVGx1RUo0Y0ZrTG02WFBROEdzCmNDNHovdk5jMVVPMXpaWVNrWWNX
            TXdsbFZHcWt2NXJLYy91UDMyeW9NMXcKLS0tIHMrQm5jb2JCaDVYQitwdEV0OWdZ
            RndDTmpWNVBwbFQ5eWtZeU5OT2lIYkEKuMyHvCtR5gpcdq5l3xMKfRof+AaJmQGr
            tX1qf6Z0nxgjVdVQGkNQ4BOAt6FMn8QXwyryzmU4agvZsyYkfxYtcw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nnmg6lemam8f87cfnhm3ffduptpjmjudq9cm064qtrkdl2jhq40qjpkaue
    lastmodified: "2026-06-25T13:42:30Z"
    mac: ENC[AES256_GCM,data:R6D8YCP6TU6NwCHYfDNP4D3k2Xd3rPaAci+QKj3ZlZDi1WrqarUFZyILLc6SqyegSGw4kibWI6nhxmubvK/z7b9pulXDgEiXag44gTreb003J5Ub98cJyoT4S/rzClf+z2nrQ45PW5fp8pNTkelCZTNlAie0ZBIrvVS6yg2bWcI=,iv:ubWEy6xTahE5av/Wn002lnbM/Derx8J+7Uzd44T2lTk=,tag:cRlwzl1reu95BebZjfYxrw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
